### ISSUE TITLE
无法获得木板

### ISSUE THREAD

**Issue by kingsey** [PIPILAN/Adventure-of-the-Golden-Warriors#1]
被木板卡进度...
JEI查询需要锯子，但做锯子又得有木板...
燧石斧提示砍原木获得木板，但尝试了各种姿势也只掉落原木Orz。
所以是配方出问题了，还是我姿势不对。

**Comment by PIPILAN** [comment]
木板用斧头右击上面，注意，这里的“上面”指的是原木六个面的上面，就是没有树皮的那一面，就可以劈柴成为木板

**Comment by kingsey** [comment]
尝试过右击侧面没想到去右击上面 (°ー°〃)
