### ISSUE TITLE
装备反重力之石游戏自动退出

### ISSUE THREAD

**Issue by solovanta** [PIPILAN/Adventure-of-the-Golden-Warriors#3]
提示服务器未开启飞行权限。感觉和之前龙卷风的问题很相似，不是说1.1.2版本修复了吗（

**Comment by PIPILAN** [comment]
1.1.2版本新建存档生效，老存档请自行修改存档文件夹下的server.properties，将
`allow-flight=false`
更改为
`allow-flight=true`
