### ISSUE TITLE
在linux系统下打开都是乱码啊

### ISSUE THREAD

**Issue by 01SW** [PIPILAN/Adventure-of-the-Golden-Warriors#4]
系统是linux mint 20.1 启动器是MultiMC
![2021-05-02_15-54](https://user-images.githubusercontent.com/29471733/116806346-e445fe80-ab5e-11eb-92b4-d38d3ec7f04e.png)

**Comment by 01SW** [comment]
不过进入游戏里面编码倒是正常了，只是菜单界面的中文出现了乱码。

**Comment by PIPILAN** [comment]
我，莫得linux系统操作经验，不知道，但我猜测是linux使用的是utf-8编码，而cmm模组是ansi编码，导致的乱码，这个我莫得解决办法

**Comment by 01SW** [comment]
我找到问题所在了，你把config/CustomMainMenu文件夹下的mainmenu.json文件编码转换为utf8就可以了。

**Comment by PIPILAN** [comment]
我知道解决方法，我上面都说了编码问题，但是windows系统用的是ANSI，windows用户更多所以我不能改成UTF-8，等我之后找到兼容办法再说吧
