### ISSUE TITLE
1.1.2版本的游戏启动崩溃问题（非已知方法能解决

### ISSUE THREAD

**Issue by phantsy** [PIPILAN/Adventure-of-the-Golden-Warriors#7]
启动游戏过程中3/7加载sound270/271时崩溃，mc显示原因mod为未知，附件为HMCL启动器测试启动数据（直到崩溃 崩溃之后我就把mc关了
[minecraft-exported-logs-2022-03-19T17-04-21.log](https://github.com/PIPILAN/Adventure-of-the-Golden-Warriors/files/8308885/minecraft-exported-logs-2022-03-19T17-04-21.log)

**Comment by phantsy** [comment]
[crash-2022-03-19_17.22.05-client.txt](https://github.com/PIPILAN/Adventure-of-the-Golden-Warriors/files/8308896/crash-2022-03-19_17.22.05-client.txt)
这个是mc的崩溃日志

**Comment by PIPILAN** [comment]
请使用非早期pcl启动器，可以选用最新版hmcl启动器，此问题是pcl启动器独有崩溃

**Comment by PIPILAN** [comment]
其他原因，已回复
